#version 300 es
precision highp float;
uniform vec2 uSize;
uniform float uTime;
uniform sampler2D uLayer;
out vec4 fragColor;

float clamp_01(float x) { return clamp(x, 0.0, 1.0); }
vec2 clamp_01(vec2 x) { return clamp(x, 0.0, 1.0); }
vec3 clamp_01(vec3 x) { return clamp(x, 0.0, 1.0); }
vec4 clamp_01(vec4 x) { return clamp(x, 0.0, 1.0); }

vec4 layerSample(vec2 p) {
  vec2 uv = vec2(p.x / max(uSize.x, 1.0), 1.0 - p.y / max(uSize.y, 1.0));
  return texture(uLayer, uv);
}

uniform float uSpeed;
uniform float uBrightness;
uniform float uContrast;
uniform float uScale;
uniform vec4 uColorFront;
uniform vec4 uColorMid;
uniform vec4 uColorBack;

//
//  SWNeuroNoise.metal
//  ShipSwift
//
//  Stitchable SwiftUI colorEffect — neuro-noise. A glowing web-like
//  structure of fluid lines and soft intersections, generated by
//  iteratively rotating UV + scale and accumulating sine/cosine waves.
//
//  Paired with: SWNeuroNoise.swift
//  Entry point: `swNeuroNoise` — invoked via SwiftUI `.colorEffect(...)`.
//  Requires iOS 17+ / macOS 14+.
//





// 2D rotation by 1 radian (baked in for speed).
 vec2 swNN_rotate1(vec2 p) {
    const float c = 0.5403023058681398;  // cos(1)
    const float s = 0.8414709848078965;  // sin(1)
    return vec2(c * p.x - s * p.y, s * p.x + c * p.y);
}

// neuroShape — 15 layers of iteratively rotated, scale-doubling
// sine/cosine accumulation. The sine accumulator threads "memory" of the
// previous layer into the next, producing the organic web look.
 float swNN_neuroShape(vec2 uv, float t) {
    vec2 sineAcc = vec2(0.0);
    vec2 res = vec2(0.0);
    float scale = 8.0;

    for (int j = 0; j < 15; j++) {
        uv      = swNN_rotate1(uv);
        sineAcc = swNN_rotate1(sineAcc);
        vec2 layer = uv * scale + float(j) + sineAcc - t;
        sineAcc += sin(layer);
        res += (0.5 + 0.5 * cos(layer)) / scale;
        scale *= 1.2;
    }
    return res.x + res.y;
}

vec4 swNeuroNoise(vec2 position, vec4 color, vec4 boundingRect, float time, float speed, float brightness, float contrast, float scale, vec4 colorFront, vec4 colorMid, vec4 colorBack) {

    vec2 sz = boundingRect.zw;
    float  minDim = max(min(sz.x, sz.y), 1.0);
    // Center-anchored, aspect-preserved UV.
    vec2 uv = (position - 0.5 * sz) / minDim;
    // Pattern zoom — small = features fill screen, large = zoom-out (more cycles per pixel).
    uv *= max(scale, 1e-4);

    float t = 0.5 * speed * time;
    float noise = swNN_neuroShape(uv, t);

    // Brightness / contrast curve.
    noise = (1.0 + clamp_01(brightness)) * noise * noise;
    noise = pow(noise, 0.7 + 6.0 * clamp_01(contrast));
    noise = min(1.4, noise);

    float blend = smoothstep(0.7, 1.4, noise);

    // Premultiply alpha for blending.
    vec3 frontRGB = vec3(colorFront.rgb) * float(colorFront.a);
    vec3 midRGB   = vec3(colorMid.rgb)   * float(colorMid.a);
    float  frontA   = float(colorFront.a);
    float  midA     = float(colorMid.a);

    vec3 blendRGB = mix(midRGB,   frontRGB, blend);
    float  blendA   = mix(midA,     frontA,   blend);

    float safeNoise = max(noise, 0.0);
    vec3 col = blendRGB * safeNoise;
    float  opacity = clamp_01(blendA * safeNoise);

    vec3 backRGB = vec3(colorBack.rgb) * float(colorBack.a);
    col = col + backRGB * (1.0 - opacity);

    return vec4(vec3(col), 1.0);

}

void main() {
  vec2 position = vec2(gl_FragCoord.x, uSize.y - gl_FragCoord.y);
  fragColor = swNeuroNoise(position, vec4(0.0), vec4(0.0, 0.0, uSize.x, uSize.y), uTime, uSpeed, uBrightness, uContrast, uScale, uColorFront, uColorMid, uColorBack);
}
